### ISSUE TITLE
How to use regular async import in webpack for non-presentational modules

### ISSUE THREAD

**Issue by jwickens** [faceyspacey/babel-plugin-universal-import#16] opened 2017-09-27 13:54 UTC
I'm using this module along with redux-first-router and react-universal-component. Besides splitting up my presentation components i really want to split up my redux middleware, epics and reducers.

I've made pretty good progress using the onLoad in react-universal-component to include the redux ware but really what I need is a way to import my redux dependencies during the thunk for the route. Then I can async include all my extra route specific redux deps, get the state, and then try to render with the universal component.

What I've found is that using this module the result of an `import` looks "wierd". When I await it returns a function rather than the whole module. I've looked at the code for both react-universal-component and universal module and i just can't wrap my head around the api that import with the plugin produces.

Is there a way to disable the babel plugin for only a few imports? I'm using webpack on both the server and the client... maybe here a short-hand way to use the result of the import ?

**Comment by faceyspacey** [comment] 2017-09-27 18:08
glad to hear you're using them all!

...there is some custom stuff there, and im gonna try to remove it in a future release. it's not a real promise, but rather an object with `.then` and `.catch` methods. Try calling them directly rather than using async/await.

I'm not the super happiest with what i had to do to preserve the promise-based API, but in the future we'll actually be dropping support for several things and can likely simplify this as well.

Probably a few weeks off.

**Comment by faceyspacey** [comment] 2017-09-27 18:32
another option is to use good 'ol require.ensure. those wont be parsed. but try regular promises first. if `.then` works, it's a good sign, and i just gotta add something for async/await.

**Comment by phyllisstein** [comment] 2017-09-29 02:39
At the risk of piling on, I've seen a similar weirdness with getting back functions that return the imported object. `dual-import` seems to work fine but `universal-import` has trouble with it. Here's a chunk of sample code that confuses `universal-import`:

```js
const importSans = async () => {
  try {
    require('vendor/fonts/din')

    if (!sessionStorage.getItem('sansLoaded')) {
      const FFO = await import('fontfaceobserver/fontfaceobserver.standalone') // would expect to get a newable `FontFaceObserver`...
      const FontFaceObserver = FFO()                                           // ...instead get a function that returns the class.
      const observer = new FontFaceObserver('PF DIN Text Pro', { weight: 400 })
      await observer.load()

      if (!__DEV__ && canStoreIn('sessionStorage')) sessionStorage.setItem('sansLoaded', true)
    }

    return true
  } catch (err) {
    console.error(err)
    return false
  }
}
```

**Comment by faceyspacey** [comment] 2017-09-29 03:48
@phyllisstein do you have the same issue if you use `import('fontfaceobserver/fontfaceobserver.standalone').then(FontFaceObserver => ...`?

**Comment by phyllisstein** [comment] 2017-09-29 05:16
I don't! Looks like this might be another `async`/`await` thing à la #14.

<img width="652" alt="screenshot" src="https://user-images.githubusercontent.com/2207980/31001695-bcd6ba48-a4b3-11e7-8e73-632f07fe299e.png">

**Comment by faceyspacey** [comment] 2017-09-29 07:40
well that's a good sign. that's what should be used for now. when i get back around to universal stuff, i'll solve it for good--likely by removing some functionality that we will no longer support, which indirectly will result in not needing some of the fancy stuff here.

**Comment by phyllisstein** [comment] 2017-09-29 10:15
Seems like a big crazy YMMV but under Babel 7 I had some success just commenting out the special `await` handling: <https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L161-L171>.

**Comment by jwickens** [comment] 2017-09-30 09:27
Client side i can import async just fine with then, which looks normal, and with await/async i do the following:

```js
const EpicsModule = await import('./epics')
const { createAsyncEpicWare } = await EpicsModule()
... do stuff with createAsyncEpicWare...
```

Wierd but it works perfectly fine

Server side it does not seem to matter which one i use, i always get this error:
```
TypeError: __webpack_require__.e is not a function
    at webpackAsyncContext (/Users/jonathanwickens/dev/humanise-web/buildServer/webpack:/src/async/pages lazy ^\.\/.*$:47:1)
    at load (/Users/jonathanwickens/dev/humanise-web/buildServer/webpack:/src/async/index.js:5:38)
    at Object.config.then (/Users/jonathanwickens/dev/humanise-web/buildServer/webpack:/node_modules/babel-plugin-universal-import/universalImport.js:8:1)
    at process._tickCallback (internal/process/next_tick.js:188:7)
[]
```

For now I'm just using the onLoad functionality in universal-component to achieve what I need. However I can't await the onLoad server side to make sure that all redux deps are included to then perform initialisation actions.

Doing it in the route thunk would actually be a lot slicker because i already await that server side and it comes with the added benefit that redux-first-router does not call the thunk again client side so i avoid calling my initialisation actions twice :).

**Comment by jwickens** [comment] 2017-09-30 09:28
Btw I'm using babel 6.26, so nothing to do with babel 7 on my side.

**Comment by faceyspacey** [comment] 2017-09-30 10:07
Awaiting onLoad is a different issue. Ultimately the webpack client side dynamic import functions will be problematic in the server.

In the future RFR will have Route level stuff to handle code splitting and all the additional things u might wanna import/do. It's one of the many reasons component level is no bueno.

You can attach stuff to your routesMap for now and then manually "flush" it FYI. Just by discovering which route will render calling and awaiting arbitrary functions you put on it. Then make onLoad simply not work server side. U could also just skip onLoad all together and do something similar with the route object client side. 

Ultimately Route level is gonna be the only way to do this at the highest level, since the highest level will involve using the new renderToString streaming API, which means u need to discover which stylesheets to serve solely based on the route before anything is rendered so u can embed them at the top of the HTML. That's where we will be going with all this, and very soon. But U can manually do all this using the thunk and onAfterChange handlers. You'd basically be a pioneer by piecing this altogether. In a few days I'll in fact adding this functionality to Rudy. So any info will be very helpful.

**Comment by jwickens** [comment] 2017-09-30 23:45
Thank's so much @faceyspacey for saying that! Really changed my thinking. I'd forgot react 16 was just released and I definitely want to get on that boat. I've switched over to react 16 and am now using RFR + flush chunks to do a pure redux method for async loading components, still early days but this is looking really nice.

Here's a snippet of my route map:

```js
export const ROUTE_MAP = {
  [constants.LOGIN_PAGE]: {
    path: '/login',
    load: loadPage('login'),
    thunk: load
  },
```

The load thunk just calls load (some other routes also do other things before or after load in the thunk). Load is separated out so on client hydration we can call load separately.

loadPage is itself an async action:

```js
const isServer = typeof window === 'undefined'

export const loadPage = (page) => async (dispatch) => {
  // this payload will be used to identify the module between redux and universal components.
  const payload = {type: 'page', value: page}
  dispatch({type: constants.ASYNC_MODULE_LOAD_START, payload})
  // import has be different here based on whether its server or client. YMMV if you use a babel server
  const mod = isServer
    ? await import(/* webpackChunkName: "pages/[request]", webpackMode: "weak" */`../../async/pages/${page}`)
    : await import(/* webpackChunkName: "pages/[request]" */`../../async/pages/${page}`)
  // register in state that we need further chunks
  dispatch({type: constants.ADD_CHUNK, payload: `pages/${page}`})
  // load any reducers, middleware defined in the module
  dispatch(loadModuleRedux(mod))
  // store the component in the state for later rendering
  dispatch({type: constants.ASYNC_MODULE_LOAD_END, payload, component: mod.default})
  return mod
}
```

The react component itself is simple, all it has to know is how to get its slice (based on payload for the ASYNC_MODULE_LOAD_* actions) and then render based on either its state of loading or by finding the resolved component in its slice of the state (breaking the rule on serialisable objects there).

On the server side once I've awaited the route thunk I can then go get all the chunks these loader actions added through `ADD_CHUNK`, and i then pass these chunk names to flush chunks.

Well that's about it. There's also a bit of work in `loadModuleRedux` which looks for mod.reducers ect to be defined.

Sorry if this got a bit off track from the repo, but I thought Id share anyway.

**Comment by faceyspacey** [comment] 2017-10-01 03:53
the only thing i'd say is you dont need all those actions.  The reducers should be smart enough to know for example that `constants.LOGIN_PAGE` is the equivalent of `dispatch({type: constants.ASYNC_MODULE_LOAD_START, payload})`

..So that's one aremoved.

then the last 3 should be combined into one. 

In short your thunk only dispatches one "follow-up action" while the initial "setup action" was synchronously handled by the system (i.e. on the server at the beginning,  or a click handler). 

----

the next stage is to provide a function like `rfr.flushChunks`. And what you do is on each route put an array of chunks that correspond to it, and then you simply grab that array off the current route. Then u can use those chunks to generate the stylesheet names and prepend the stylsheets to the top of your HTML before you even start rendering. That way you can render to a stream for optimum performance.

**Comment by faceyspacey** [comment] 2017-10-01 04:31
also, one other thing:

if one route has the ability to produce multiple chunks, you need to put a function on `route.chunkNames` and pass it params similar to what `thunk` receives, or perhaps just `state`. That way you can use the payload of the current action to determine the chunks. For example:

*server/configureStore.js:*
```js
const routesMap = {
    FOO: {
        path: '/foo/:param',
        chunkNames: locationState => {
             const upperCaseFirstCharacter(locationState.payload.param)
             return [chunkName])
        }
    }
}

const { thunk, etc } = connectRoutes(routesMap)
const store = createStore()

let location = store.getState().location
if (doesRedirect(location, res)) return false

await thunk(store)
return store
```

*server/render.js:*
```js
export default ({ clientStats }) => async (req, res) => {
   const store = await configureStore(req, res)
   if (!store) return

   // this is like react-universal-component/flushChunks, but at the route level.
   // essentially RFR will have a method named: `rfr.flushChunks()` that does this:

   const type = store.getState().location.type
   const chunkNames = routesMap[type].chunkNames(store.getState().location)

   const { styles, js, cssHash } = flushChunks(webpackStats, { chunkNames })

   // notice we can now render to string/stream after flushing now!:

   const app = createApp(App, store)

   res.write(`<!doctype html>
      <html>
        <head>
          ${styles}
        </head>
        <body>
          <div id="root">`)

   const stream = renderToNodeStream(app);
   stream.pipe(res, { end: false });

   stream.on('end', () => {
    res.write(`</div>
          <script>window.REDUX_STATE = ${JSON.stringify(store.getState())}</script>
          ${cssHash}
          ${js}
        </body>
      </html>`);
    res.end();
   });
}
```

So anyway it comes out pretty cool. The idea is we still use `webpack-flush-chunks`, but instead of getting `chunkNames` from react universal component, we get it at the *"route level"* via RFR!

And of course this all plays out for a very specific business purpose: **to send the layout of the page + all styles before the stream begins.** That way the layout and the content rendered in the stream itself has all the styles it needs from the beginning, without having to fully render to discover the complete list of styles. 

Ultimately, to do this at the highest level, you can send the initial layout of the page immediately at the very beginning of the request, before awaiting thunks server side. I.e:

```js
res.write"(<doctype> etc...")
await thunk(store)
```
You'll of course want to get the initial state of the route to insure it's not a redirect, but immediately then you can start sending stuff to the client, which browsers will begin to render immediately, i.e. without closing tags, i.e. without the entire content. It's a major win for React SSR. And you can do all this before RFR automates it for you, pretty much just as above.

Make sure to read this article:
https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67

ps. this is the first this plan has been publicly shared :)

i got a few more things to finish before we get to this, primarily pre-fetching thunks/chunks. With the `chunkName` key you will be to prefetch chunkNames of the next route (as well as their thunks!). i.e:

```js
const routesMap = {
    FOO: {
        path: '/foo/:param',
        prefetch: ['BAR']
    },
    BAR: {
        path: '/bar',
        thunk: (dispatch) => fetch().then(payload => dispatch({ type: 'NEW_DATA', payload })
        chunkNames: locationState => {
             return ['asyncComponents/Bar']
        }
    }
}
```

That's a basic example, but basically there will now be a `prefetch` key as well. And it can specify an array of other routes to prefetch. Obviously it can get more complicated than that, as you'll also want to be able to specify the assumed payloads, which might be needed to generate chunkNames and data from thunks. And of course it too can also be a function. It will primarily be used as a function since you have to think most routes have payloads, so the only way to know what the upcoming route's likely payload is, is by the payload of the current route--just like links on a page. 

The other thing to note is that `prefetch` is solely a client side feature.

**Comment by jwickens** [comment] 2017-10-01 21:16
This is all super cool, the next version of RFR is going to be amazing! That prefetch feature will also be really helpful.

I guess why I have so many redux actions was to break up the different things i have to do on top of RFR. I also find using pure redux actions and reducers really understable and enjoyable in my own setup. Rather than using a function to map the route to a set of styles, dispatching "add chunks" and then getting the chunks out of the state is just so simple, and it allows easy composition of multiple or nested loaders.

I also think "thunk" is no longer descriptive in the api as-is. Its necessary to distinguish between different thunks for different stages:
```
* entryCheck: optional, to check authorization for example and issue a redirect, skipping other stages. RFR should call this recursively until it the entry check passes.
* load: loads all async components and redux ware for a route. On the server additional state chunkNames are provided. On the client it updates the loading state for the route.
* initialization: called on the first load, also detects hydration for skipping on ssr
```

Basically you dont want to load if you dont pass the entryCheck, you always want to load, and you only perform initialisation one.

This could allow one additional optimisation: sending the styles before performing initialisation functions that are likely fetching data.

```js
export default ({ clientStats }) => async (req, res) => {
   const { store, initializeRouteAction } = await configureStore(req, res)
   if (!store) return

  const { serverOnly: { chunkNames } } = store.getState()
   const { styles, js, cssHash } = flushChunks(webpackStats, { chunkNames })

   res.write(`<!doctype html>
      <html>
        <head>
          ${styles}
        </head>
        <body>
          <div id="root">`)

   // while our client is loading style sheets the server is fetching data for the first view
   await store.dispatch(initializeRouteAction())

   const app = createApp(App, store)
   const stream = renderToNodeStream(app);
   stream.pipe(res, { end: false });
   stream.on('end', () => {
    res.write(`</div>
          <script>window.REDUX_STATE = ${JSON.stringify(store.getState())}</script>
          ${cssHash}
          ${js}
        </body>
      </html>`);
    res.end();
   });
}
```

**Comment by jwickens** [comment] 2017-10-02 11:33
So I ran into one more thing I forgot... loading the CSS. I tried the dual import plugin but that lead to the same problems as above. 

Instead I've setup some more redux state and actions to replicate what the plugins were doing.

Here's a redux log of what happens client side on SSR for the login page, followed by switching to the dashboard.

![screen shot 2017-10-02 at 13 06 15](https://user-images.githubusercontent.com/5220075/31074820-b35d017c-a772-11e7-9a87-e11e9d1af86f.png)

Note a separate hydrate action is required because on the initial load of state when configuring the store client side, extra reducers in the "async modules" are not available, so that state gets ignored.

In the render server side I use an action pass the raw css hash from flush chunks into redux:

***css-actions.js***
```js
export const registerCssByChunks = (cssHash) => (dispatch, getState) => {
  const { serverOnly: { chunks } } = getState()
  dispatch({
    type: constants.ADD_CSS_BY_CHUNK,
    payload: cssHash
  })
  chunks.forEach(chunk => {
    dispatch({
      type: `${constants.LOAD_CSS}_FULFILLED`,
      payload: { chunkName: chunk }
    })
  })
}
```

**Comment by faceyspacey** [comment] 2017-10-02 12:33
The chunks should be flushed and available on first load. those chunks should have any async modules you need. if for example you were just using `babel-plugin-universal-import` and react universal component + webpack flush chunks, you could export additional things like the redux stuff from the component file. 

As far as the multiple actions thing, the idea is you got a function that takes a `(page)` param. Then you remake actions and payloads based on that. But you get that same param in the route thunk. So it's a matter of making your reducers smarter to respond to that same action. It's the same thing, just less actions, smarter/fatter reducers. You make the reducer that returns components return strings of the components, and just get them from a global hash somewhere in your component tree.

The RFR way isn't dispatching all this async-related stuff like you're doing. I'm not sure exactly what's different about your setup that makes you want to do this. You're also dispatching all chunks you already have in state in a `forEach`. I'd make the hash have the ones u already have (i.e. `loaded`) marked as true and dispatch once. I personally don't trust redux running so much. Performance is horrible when it comes to animations. React 16 improve it, but the browser sucks, and I don't care what anyone else says. I've experienced and spent literal years optimizing on both React Native and web for redux/react updates during animations. So it's horrible for performance. You want to dispatch the least amount of actions, which updates the store the least, and triggers the least re-renders. You're not only updating the store, but getting re-renders as a result. In addition, it's a ton more imperative logic that could just live in smarter/fatter reducers. `items.forEach => dispatch` I would never do or recommend. You don't want that. What you want is to send the data once in a single action and have your reducers interpret it. It reduces the # of actions and simplifies your application greatly. Ultimately the simplification is more important than the performance.

Also, you know RFR supports "pathless routes" now, right? Check the top of the RFR readme. So you don't need to create traditional thunks. Everything can live under one `routesMap`. That also means you don't need to dispatch functions/thunks from components anymore, or have react-redux prepare em, etc. You can just *always* dispatch sync actions (similar to Sagas and Redux Observable), and have Redux-First Router map it to a thunk function. Perhaps more importantly, the "setup action" of a traditional redux thunk is now automatic and implicit. It's the sync action you dispatch. In traditional redux-thunk, you dispatch a function, then inside that function you dispatch a "setup action" and then do some async work and then the "follow-up action." That's 3 dispatches. With RFR it's just 2.

I don't think awaiting your component in a thunk is the way to go. That's double the work--because the component has to do it as well. Of if your components are getting it out of a reducer like i think you're doing, you're essentially missing out on all the automation and features of something like react-universal-component. It means you gotta build the related stuff from scratch. That's totally fine, and may just boil down to handling when to show the spinner on your own. Just wanted to point that one out. I'm not sure how I feel about that one. You could be on to something, I just don't know right now. For now though, it means rebuilding more things from scratch, as RUC has a lot more features than just showing a spinner.

As far as the additional thunks. We actually have these (and will be released today or tomorrow):

- beforeEnter
- thunk (tho may have onEnter as an alias)
- afterEnter
- beforeLeave
- onLeave

And they will all exist globally and for each route. 

That leaves one more problem, which you brought up: doing auth in conjunction with streaming without running everything in the middleware, particularly the async work. Basically The problem is that you'd like to be able to do `res.write` with the head of your page immediately, but you can't do that if there may be a redirect. That leaves you running your thunks before you start streaming things *just to see if you have any redirects*. So as you pointed out we may need another callback or feature for this to find out which routes redirect *separately from their data-fetching capabilities*. I mean basically u can get around it in your own app with a set of simple rules: 

- if the route is a public route (i.e. is marked as `route.public`), stream immediately
- if route is marked as `route.private` validate the jwt token first thing before running through the RFR middleware, and then stream
- if the route is marked as `route.private` and there is no valid jwtoken, perhaps run the middleware and let it determine where to redirect to; or perhaps you simply know, and then just redirect to `/login` immediately.

So this is all easily done in userland. The goal is to find a flexible enough way to build into RFR that can work for enough use-cases. `beforeEnter` can handle it--you just have to make sure not to also use it for other async work. So we may already have the recipe. But I do like the idea of something built in for redirects and auth stuff. In fact, that's what I'm working on right now. I'm thinking of how to short-circuit the middleware as soon as possible. Here's what i'm thinking:

```js
  const middleware = (store: Store) => (next: Next) => (action: Object) => {
    if (isServer() && isRedirect(action)) return action
```

Previously you had to do `getState()` after the middleware runs on the server, but even that requires all your reducers to run. To do this at the highest level means not running all those reducers unnecessarily, and definitely thunks and other middleware stuff. We have the recursive `route -> thunk -> redirect -> another route -> thunk` thing now. So as soon as one of those actions is a redirect, we should short-circuit. The one challenge with that now is simply some of your route thunks may return other things (perhaps the result of an api request). Then you have to detect if the return is an action etc.

Here's how it works now on both the server and client in the upcoming release:

```js
const action = await dispatch(firstRoute())
```
> so no more `await thunk` just on the server. No more automatic dispatching of the first route on the client. You always have to dispatch the `firstRoute()` action creator. It's smart enough not to re-run thunks on the client if you already have SSR. But it's needed in that case to insure a few other middleware tasks are handled. So it was determined to be most consistent to always have to do that, especially since people using Sagas always had to do that via the `initialDispatch: false` option + `initialDispatch()` action creator. That action creator is now gone. so is the `thunk` return. And now it's consistent everywhere, and therefore more accessible and easier to remember. And explicit.


On the server, you'd do this if we move to returning the action and not letting the whole middleware resolve:

```js
const action = await dispatch(firstRoute())
if (doesRedirect(action)) return false
```
-----
Anyway, lots to think about to do this perfectly, which is why i was bringing up those things about how ur doing it. If ur absolutely right about the multiple dispatch approach, etc, i wanna know about it. But from my standpoint it's not currently, and it's not going to be in the near-future, the promoted RFR way. And I think there very much is a *way* here. 

Dispatching entire asynchronously received modules could be, but all the dispatches definitely not. They're simply not needed. It means more code to maintain, and a decrease in performance. This is the cusp man. Rudy is the future of React development. For the 80% use-case that most developers use. Dumb components. Inherently dumb reducers. That will mean your most complex logic lives in the "controller" layer, i.e. Rudy. The whole thinking is that components and reducers stay dumb. And i mean you build 100% of your app out of dumb components if you can. If you gotta make an exception to mount a high chart in a lifecycle handler fine, or over-coming a browser bug, fine, but the rest is stateless functional components. That's how they do in clojurescript btw. And it's the right way. 

The problem for React proper and JS is that on one end of the spectrum we have super experts preaching component level through Relay, Apollo and GraphQL, and then we have learners going component level as well (but without those nifty abstractions), and then they run into a bunch of problems where 99% of them are doing things like dispatching redux actions in componentDid/WillMount--when really the correct pattern is to dispatch the actions only on events like clicks and taps. Those learner developers (which are ultimately larger percentage of developers than experts, given the pyramidic nature of increasing one's skills) end up in a world of hurt. I've seen a lot of these apps. They're fucking horrible. And these developers are in pain. Most don't fully grok that proper Redux usage means **stop using lifecycle handlers to manipulate state**. 

The reason is simply this: middleware is complex, piecing it together with React Router is non-obvious, and there isn't a redux-first router that establishes an obvious idiom (until recently). Hit youy routes, let Rudy control what happens, your model updates, and then your views. Tap a link to another page, don't think twice about how you're gonna simultaneously dispatch some async actions (i.e. put em in your routes map), and make your dumb components and reducers respond as they should. 

The future of React develop as I'm trying to make it is a world where your most complex work is in your controller. And it's a far better world because you don't end up with the mess people have in their components these days. 

A key ingredient to this world is less actions. For example, where does your thunk that takes that `(page)` parameter live? Where does it get called? If it's not in a route, that means you gotta insure all those actions are also dispatched if the user presses the back/next buttons or visits the route directly. Same on RN with deep linking and push notifications. Fine, you got route thunks and other callbacks--at least that solves it. Before without that, people ended up using lifecycle handlers to dispatch all that stuff when u arrived on a route that rendered that component. 

The point is the route becomes the controller of the whole setup. It dictates what's needed to reproduce the exact state it will need. **And this allows you to reach the route in any way possible**--not just when the user clicks the right button with the correct onClick handler in a previous component. 

So taking that mantra all the way means minimizing the amount of work you're doing in your route thunks (or the other new callbacks we have now). You already have the "setup action" dispatched by virtue of the fact that the route was hit. Any state that can be achieved via its payload, type, etc, should be handled by the reducers immediately (not in another action). 

There's only one thing u should do here: things that reducers cant do. I.e. async work. 

The reason is reducers are dumb. Dumb is a good thing. When things are dumb/pure, it means following their logic is easy. You start detracting from that inherent simplicity when you start dispatching more actions. And ultimately async data fetching is going to be the most complicated part of your app.

Dumb pure synchronous functions (i.e. components and reducers) are easy. Async functions/thunks that basically mutate state and make multiple function calls, dictating multiple code-paths are complex. *And* they do mutate state. Even tho it's done through a predetermined mechanism: `dispatch` and the mechanics of redux, your thunks are basically the one place that mutates state. 

Sure if you're doing it correctly, you're doing it based solely on the payload, type, etc as just mentioned. BUT, the code still looks like typical spagetti code from the OOP/procedural/imperative days of old. Thunks are essentially a random list of directives of things to do, which may or may not even be related--whereas reducers and components are focused on a `return`. On an output. A pure output. **So even tho thunks are `pure` on the *input*, they aren't on the *output*. Reducers and stateless components are pure on both sides.** 

Ultimately the `thunk` and other callbacks will be doing things like scroll restoration, triggering modals, telling tracking tools like Mixpanel what happened, etc. So these `thunks` are already quite complicated. According to the direction of Rudy, it's the only place that isn't pure on both inputs and outputs. Anything that is pure on inputs and outputs like components and reducers is "easy" by that very nature. So given that components now have a reduced role in terms of the work they will be doing, more of this work will end up in route thunks (or pathless route thunks), or the other aforementioned new callbacks. We're cleaning up the mess in one place and isolating it and moving it to another, the same way you efficiently sweep up messes on the floor. We have 2 boxes checked, now we gotta setup for a scenario where our thunks/etc also don't lose shavings and dust-balls and become un-ordered. To prepare for that world, we must make our focus to do as few dispatches as possible. That will cut the size of those thunks in half or perhaps by 3 quarters or more. Shift everything that can be done in a pure environment--without making it impure--to the pure environment. That's the mantra in a nutshell.

**Comment by faceyspacey** [comment] 2017-10-02 12:36
now that all said, i do find it really interesting having those cssChunks (and imported components themselves) living in Redux *state*. That's definitely a fresh take. I think you're on to something with that. Not sure if we need all the actions. And simply it might just be something perfect for Rudy to do for you.

**Comment by jwickens** [comment] 2017-10-02 22:37
I must admit I also find my current setup a bit spaghetti, some of the new features in Rudy will help a lot to clean that up. Also what you're saying about less actions definately sounds worthwhile. I am getting a big of jank with switching between chunks and my guess that you're saying about the render is definately true. Will look to simplifying that a lot. BTW Regarding the for each to batch send my actions... normally I don't do that! I have a batch action reducer and corresponding action that I use during my async actions.

I have a ton of middleware and enhancers in my redux setup and I really appreciate/need each one. observables, async (which dispatches only 2 actions), optimist (for optimistic updates), responsive for detecting the screen size. Needless to its quite a complex setup and for something like a login page most of its not needed. So loading a what a call a module comes with a react component, css, and a bunch of redux stuff.

So yes I am loading my component from the redux state in my async loaded react components. Its great! It results in a really dumb pure functional component to show either that its loading or to pass the result through from redux-connect.

**Closed as completed** 2017-10-11 19:44 UTC

**Comment by phyllisstein** [comment] 2017-12-02 02:43
Just flagging this as still broken, in precisely the way described above: <https://github.com/faceyspacey/babel-plugin-universal-import/issues/16#issuecomment-333015917>. With `universal-import` included in the Babel plugins, standard `async`/`await` calls don't return the `await`ed value, but a function that, when called, returns the `await`ed value.

In the app I've been developing, we use `async`/`await` heavily to smooth over Promises, which means we can't use this plugin. But without this plugin, our stopgap solution (adding the `universal` callback and Webpack `resolveWeak` calls by hand) breaks HMR. We're kind of backed into a corner.

I'd love to submit a PR but I'm not sure I understand what case <https://github.com/faceyspacey/babel-plugin-universal-import/blob/a6e220e31e4c65661fd9e88a321b0fd5bfbf8838/index.js#L190-L202> is covering well enough to preserve the intended behavior. As I mentioned above, ripping it out altogether seems to do wonders.

**Comment by faceyspacey** [comment] 2017-12-02 09:48
Based on the test snapshot, it looks like the issue is that in this particular case a function doesn't need to be passed to `universalImport`:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/a6e220e31e4c65661fd9e88a321b0fd5bfbf8838/__tests__/__snapshots__/index.js.snap#L17

Instead of this template:
https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/index.js#L173
we should simply rewrite another one like this:

```js
const awaitLoadTemplate = template(
    'Promise.all([IMPORT, IMPORT_CSS(MODULE, CSS_OPTIONS)]).then(proms => proms[0])'
  )
```

Notice `() => ` is now gone. That seems to be the precise issue described here: https://github.com/faceyspacey/babel-plugin-universal-import/issues/16#issuecomment-333015917 

And it shouldn't break anything else.

**Comment by phyllisstein** [comment] 2017-12-02 16:37
Thanks so much for the pointer 💖! (_Always_ read the tests, Daniel, schoolboy error.) I'll try to get a PR up this weekend with additional test cases for the vanilla `async`/`await` behavior.

**Comment by phyllisstein** [comment] 2017-12-02 19:15
That path took me a bit farther, but I think it's creating a circular dependency in Webpack. When I use `async`/`await` to load the main application bundle, it throws this error:

```
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_8_react_universal_component___default(...) is not a function
    at Object.<anonymous> (https://dugan.cutty.dev/assets/js/app.js:42578:78)
```

Switching back to a synchronous `require` resolves it (though Universal Component complains that `load` isn't a function).

It strikes me that the _ideal_ solution would be to only manipulate `import` expressions that occurred as arguments to a call to Universal Component, but given that the local identifier lives in userland I can't think of a way to find it without walking all the import statements from the module root, as `babel-plugin-lodash` does.

**Comment by faceyspacey** [comment] 2017-12-02 19:33
In the future I'll rewrite it to make use of bindings to modify the options arg passed to universal instead. I did it this way because I wanted the babel plugin to be as fast as possible, but the costs in complexity of code are too high. It has to change, but that won't be for a few more months.

----
How are you using async/await before your bundle is ready? I guess it's all polyfilled etc just prior via another way or vendor bundle.

Does async/await work in a simpler more isolated case than when importing the entire main bundle? 

What will really help is logging the transformed code from within babel-loader before webpack changed it entirely. If you add a console.log to the file in nod_mosules, your terminal will get filled with text; so you will need to search it for relevant words like "universalImport" to find the relevant code.

After that, compare it to the final webpack output. At one of these stages something incorrect with the transformation will become visible. The logged errors in this case are only a small part of the story.

**Comment by phyllisstein** [comment] 2017-12-03 16:06
Sure, that makes sense. Is that an effort that I could kick off, or help with? Obviously we've both got lives and day jobs and other pressures, and I'm very new to Babel's innards, but I'd be more than happy to give some time and energy back to a project that's been so useful.

---

I was a little unclear: the bundle's entrypoint is one of the places we drop `async`/`await`, to guarantee that things like polyfills are available before the main application loads. So it'd look something like this:

```js
// client.js
;(async () => {
  // Polyfills, animation globals, and all that jazz.
  if (!('requestIdleCallback' in window) || typeof window.requestIdleCallback !== 'function') {
    await import('requestidlecallback')
  }

  // Boot the React app.
  await import('app')
})()
```

We want to define split points for large libraries, especially when they're conditionally required, but choreograph their load order so that they're available to the main application, so `await`ing `import` expressions seems like the way to go.

The problem is that the "vanilla" `await` expressions get caught in this plugin's net, so that Babel transforms that code snippet into:

<details>
  <summary>Babel output w/ Universal Import</summary>

  ```js
  var _importCss = _interopRequireDefault(require("babel-plugin-universal-import/importCss")).default;

  var _universalImport = _interopRequireDefault(require("babel-plugin-universal-import/universalImport")).default;

  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

  // client.js
  ;

  (async function () {
    // Polyfills, animation globals, and all that jazz.
    if (!('requestIdleCallback' in window) || typeof window.requestIdleCallback !== 'function') {
      await _universalImport(function () {
        return Promise.all([import(
        /* webpackChunkName: 'requestidlecallback' */
        'requestidlecallback'), _importCss("requestidlecallback", {})]).then(function (proms) {
          return proms[0];
        });
      }, false);
    } // Boot the React app.


    await _universalImport(function () {
      return Promise.all([import(
      /* webpackChunkName: 'app' */
      'app'), _importCss("app", {})]).then(function (proms) {
        return proms[0];
      });
    }, false);
  })();
  ```
  
</details>

Ideally, I think, those non-Universal `await` expressions would be left untouched. I think there's a hacky way to do it with the plugin's current architecture---you could step up a fixed number of `parentPath`s and check to see if there's a `CallExpression` roughly where you'd think it would be---but it didn't strike me as the best answer. 🙁 

---

**EDIT:** No, I lied, that's not quite right is it. We want to be able to flush even the non-Universal chunk names back out synchronously for SSR, so we need this wrapper. So maybe the answer is just to fix the circular dependency?

**Comment by faceyspacey** [comment] 2017-12-08 02:10
Hey @phyllisstein I just moved this week, so I've been MIA. Honestly I'm super focused on getting the next version of Redux First Router out, and plan to circle back to this and give it a major revamp. It's killing me inside to try to find the time for what will just be a temporary solution. In the next version we'll circumvent this issue via the aforementioned usage of bindings or other similar solutions.

**Comment by phyllisstein** [comment] 2017-12-08 05:39
Congrats on the move! And no worries---we'll make do for now. Please do ping me if I can be useful in your efforts though. 💖

**Comment by buzinas** [comment] 2019-04-12 14:55
Why is this issue closed? I read the entire thread, and it seems that it's still impossible to use regular `async`/`await` for importing modules, which is a bummer. Or am I missing something?

**Comment by ScriptedAlchemy** [comment] 2019-04-12 18:05
@buzinas This is a very low priority on my radar. Always willing to accept PR's but there are newer, more advanced things on the way which ill be using to replace Universal. Babel isn't my strong suit either, Im facing a similar async issue I might need to patch in another plugin - if I do patch it there, ill look at rolling it here

**Comment by buzinas** [comment] 2019-04-12 20:31
My main problem is that I my project uses `react-static`, which uses `babel-plugin-universal-import` under the hood (only in production). I can use `async`/`await` in development, but when I deploy it, the problem underlined in this issue happens (the dynamic import returns a function, instead of a promise). If I workaround it by calling the function it returns, everything works – but only in production, and then my development environment breaks. So the only solution for my problem at this time is:

```js
let myModule = await import('my-module')
if (typeof myModule === 'function') myModule = await myModule()
```

Then it works in both environment, but this is a very very ugly hack.
Dynamic import should just work, I can't see why it doesn't at all.

If you can give me any guidance on how to proceed, I'll definitely come up with a PR, but I can't quite understand this plugin behavior, so I really need some kind of help.
