### ISSUE TITLE
[ Workaround ] Nested Universal Imports results in composed chunkNames

### ISSUE THREAD

**Issue by Aetherall** [faceyspacey/babel-plugin-universal-import#15] opened 2017-09-18 07:14 UTC
The current behaviour when nesting Universal Imports ( or in my case Universal Components ) is that a 
 split child herits his chunkName from his parent 

e.g :
 
file1 => ImportAsync => file2 => ImportAsync => file3

results in the following chunks :

- main
- file2
- file2-file3

Awaiting a better solution, ( I do not have the time right now to do it myself but maybe later )
I replaced the chunkName template to permit the use of a prefix
````javascript
    () => MODULE
// to
    ()  => typeof chunkNamePrefix !== 'undefined' ? `${chunkNamePrefix}${MODULE}` : MODULE
````

So to get it working you have to define a chunkNamePrefix variable in the scope as follows

````javascript
import universal from 'react-universal-component'
const chunkNamePrefix = 'file2-'
const UniversalComponent = universal(props => import(`./${props.page}`))

<UniversalComponent page='file3' />

      ↓ ↓ ↓ ↓ ↓ ↓

import universal from 'react-universal-component'
import universalImport from 'babel-plugin-universal-import/universalImport.js'
import importCss from 'babel-plugin-universal-import/importCss.js'
import path from 'path'

const chunkNamePrefix = 'file2-'

const UniversalComponent = universal(props => universalImport({
  chunkName: props => typeof chunkNamePrefix !== 'undefined' ? `${chunkNamePrefix}${props.page}` : props.page,
  path: props => path.join(__dirname, `./${props.page}`),
  resolve: props => require.resolveWeak(`./${props.page}`),
  load: props => Promise.all([
    import( /* webpackChunkName: '[request]' */ `./${props.page}`),
    importCss(page)
  ]).then(proms => proms[0])
}));

<UniversalComponent page='file3' />
````

I agree It's not fancy and I will mind hug the one who comes with a PRable solution

#13 seems really great but I would really enjoy to keep '[request]' as the webpackChunkName so I dont need to manually define each one of my imports in the comments

Hope it will help someone

Here is the fork : https://github.com/Aetherall/babel-plugin-universal-import

**Comment by faceyspacey** [comment] 2017-09-18 07:24
Honestly, i cant figure out what you're trying to do by this. I don't understand what you mean by "nesting". Using a component inside of another should not be the cause of any issue. What likely is--especially if you're having hyphens appear in your chunk names--is the file structure. When using dynamic expressions, the only real and best way is to create a folder that contains nothing but async components. The real problem is that webpack will generate chunks for every file for in the folder (even, if say they are a .css file). Then if you have sub-folders, it will recursively create chunks for those. This is a problem because you likely only want chunks for a sub-set of those files.

Now, i can't quite figure out what you're trying to do, but my best guess is you create a folder like this `/components/async` and only put entry point components, you will solve your problem.

**Comment by Aetherall** [comment] 2017-09-18 11:23
In fact I would like keep my code as If I wasn't using Universal Imports

I keep my UniversalComponent code in a separate folder, and use it as a dependency

````javascript
// somewhere in my app
import { UniversalComponent } from 'omni:core';

<UniversalComponent import={() => import(`./${routes[props.location]}`)} />
````
````javascript
// in omni:core/universal
import { addRoutes } from 'redux-first-router';
import universal from 'react-universal-component';

const UniversalComponent = universal(props => props.import(), {
	onLoad: (module, info, props, context) => {
		if (module.routes) {
			const thunk = addRoutes(module.routes);
			thunk(context.store.dispatch);
		}
	},
});
export default UniversalComponent;

````

**Comment by Aetherall** [comment] 2017-09-18 14:36
Oh I thought I got what you said but I didn't
Indeed webpack now splits every import into chunks

Shame on me I missed that ><"

In fact I would like to tell webpack which file put into which chunk by using regular or universal imports

So I can split my app into many parts, each one with it's own purpose and without make my client download useless stuff

but in the same time I want to keep my code consistant and keep my folder hierachy the same, because the purpose of my app is to be updated everyday for an increasing number of use cases ( kinda framework )

the best would be to use universal import to split chunks and then regular imports to import in the same chunk

The solution may be on the webpack side so I will look in that direction first

**Comment by faceyspacey** [comment] 2017-09-19 00:45
make a folder called `/async` with files that are one line that require from for example: `/components/Foo/index.js`. 

Im assuming ur doing that pattern where you have folders that contain multiple files that correspond to a primary component. 

If you want to use dynamic expressions, this is the best way to do it. You can also use the webpack context replacement plugin to limit what files generate chunks, but I havent actually tried it. So if you got that working u could possibly avoid the extra chunk creation without having to make a new basically pointless folder.

**Comment by faceyspacey** [comment] 2017-09-29 07:43
closing this. others have had success with the context replacement plugin for similar issues:

https://github.com/faceyspacey/react-universal-component/issues/50

**Closed as completed by faceyspacey** 2017-09-29 07:43 UTC
