### ISSUE TITLE
v1.5.2 breaking change

### ISSUE THREAD

**Issue by tkomstadius** [faceyspacey/babel-plugin-universal-import#45] opened 2018-04-27 12:30 UTC
Is it expected behaviour that the build output should be flattened? 
If so, shouldn't that be at least a minor, preferably a major? This was a breaking change for us. 

Our output structure v1.5.1
```
dist/
    client/
        components/
             component.js
        containers/
            container.js
```

Our output structure v1.5.2
```
dist/
    client/
        component.js
        container.js
```

Thanks!

**Comment by faceyspacey** [comment] 2018-04-27 16:20
Sorry about that. If should have been major. Next week I’ll see what I can do.

**Comment by zackkirsh** [comment] 2018-04-29 05:30
@tkomstadius Thanks for raising this, it looks related to some work i did regarding nested chunknames. 

May I ask, currently what does your import structure look like? 
`universal(import('../components/component.js'))` ? what did the chunkname look like that you were loading?

I can investigate this and see if theres a viable solution.

@faceyspacey any objections or do you want major bump? On a side note, i did roll back the version 1.5.1 confirm that i wasn't going crazy.

`<UniversalComponent page="NestedExample/NestedComponent"/>` or `<UniversalComponent page={import('./NestedExample/NestedComponent')}/>` does not work for me. Given the scenario i originally patched. Ill check the webpack chunk output and see if theres another way to resolve the chunks? Let me know your thoughts

**Comment by faceyspacey** [comment] 2018-04-29 19:48
@zackkirsh I think the flat structure makes sense. It's what I always wanted, but I deferred to how webpack was handling it. We just need to make sure that if multiple chunks have the same file name they can't overwrite each other.

Since it's been longer than 24 hours, I can't unpublish a version, so I emailed in a request to the NPM registry, as per:

https://docs.npmjs.com/cli/unpublish

If that doesn't work out, we'll publish 1.5.3 to be the way it was, and then 2.0.0 to include your latest PR.

----
As far as `page` representing multiple path segments, I actually cant remember right now if you could do `dir/file` or if it just had to be `file`. I'm also not quite sure that's what you're asking. That said, I'm pretty sure we always did support it. As far as passing the `import()` promise, that's likely why you were getting the flash and checksum mismatch in your RUC issue--that can't resolve server-side. RUC isn't designed to handle that universally; it's just something that happens to work in SPAs.

**Comment by zackkirsh** [comment] 2018-04-29 20:36
Okay, thanks for your input here! I believe, in all honesty, that webpack's conventions are also changing to a more flattened file structure - so i too am happy with this (and kinda though it was always like this, which is why i didnt think to check the output).
If you look at WP4 chunking. Its using relationships, to other modules to generate chunknames, having folders would / could cache bust something that doesn't need to be. 



Regarding you comments around multiple path segments. I honestly dont know if the multiple directory thing did work. Ive followed your project for a long time but typically didnt build over complex things with universalComponent, mostly just route based page verticals and such. Im pretty sure the one to blame is webpack though. The new chunking in WP3 looks like the one responsible to breaking. 

I know my passing import() as a prop is a very unorthodox implementation of whats intended. However i didnt have to open a PR *specifically* for that, ive mostly handled that in my own code. 

As mentioned elsewhere, ill PR new tests for nested imports what look more normal

Heres the code in which im using import as a prop

```
// util.js
const determineHowToLoad = (props) => (typeof props.component !== 'string') ? props.component() : import(`./${props.component}`);

const UniversalComponent = universal(determineHowToLoad, {
    onError: (error, {isServer}) => { // eslint-disable-line no-unused-vars
        throw error;
    },
    loading: () => null,
    error: (e) => {
        console.error(e); // eslint-disable-line no-console
        return <div/>;
    }
});

// index.js

<UniversalComponent component={() => import('../ExtraAssets/SomeComponent')}/>
```

This works perfectly with no flashes (unless you are referring to the issue i opened on universal-component)

**Comment by tkomstadius** [comment] 2018-05-02 11:58
@zackkirsh we import from paths that are resolved with webpack, like so  `universal(import('components/viewHelper/carousel/Carousel'))`.

But we do not have a problem with the flat output structure only that it happened without us knowing it. 🙂

**Comment by ScriptedAlchemy** [comment] 2018-05-02 23:02
@tkomstadius no problem, Im surprised nested importing like that is working for you. Whats your webpack version?

**Comment by tkomstadius** [comment] 2018-05-03 07:45
@zackljackson We are using 3.11

**Comment by faceyspacey** [comment] 2018-05-04 10:53
#### UPDATE:

I had contacted NPM and was waiting to see if they would unpublish 1.5.2. Basically the answer is they are hesitant to do it because other packages depend on this package.

So now we have 1.5.3 which reflects the old nest structure, thanks to @zackkirsh 's revert PR (https://github.com/faceyspacey/babel-plugin-universal-import/pull/46).

His follow-up PR (https://github.com/faceyspacey/babel-plugin-universal-import/pull/48) will be merged shortly, which will reflect those changes on 2.0.0.

1.5.2 has been deprecated, so if you try to use it, you will be notified in the terminal, and probably see a message similar to:
![screen shot 2018-05-04 at 3 59 45 am](https://user-images.githubusercontent.com/154732/39624851-b1d8115e-4f4f-11e8-8b37-73519f985bab.png)


Sorry about the inconvenience everyone.

**Closed as completed by faceyspacey** 2018-05-04 10:53 UTC

**Comment by dtonys** [comment] 2018-05-20 00:59
My css does not load, due to updating `babel-plugin-universal-import` from `1.4.0` -> `2.0.0`, 

Spent a few hours trying to resolve this, I've tracked this down to be the root issue.

I'm using the universal import like this:
`const HomePage = universal(import('pages/Home/Home'), options);`
https://github.com/dtonys/universal-web-boilerplate/blob/94b973f3ca93bc6136d24d2078e4682ae278ebb2/src/components/Page/Page.js#L24

I'm loading my CSS like this:
`import styles from 'pages/Home/Home.scss';`
https://github.com/dtonys/universal-web-boilerplate/blob/94b973f3ca93bc6136d24d2078e4682ae278ebb2/src/pages/Home/Home.js#L7

I'm using `resolve.modules` in my webpack config to allow loading modules from `src` instead of a relative path:
```
    resolve: { modules: [ PATHS.src, ],
```

Checking the `window.__CSS_CHUNKS__` for `1.4.0` (working) , I see this:
```
{
  pages/Signup/Signup: "/static/pages/Signup/Signup.7656d3ca4adc6fd6127d1e9100985d9a.css",
  pages/Login/Login: "/static/pages/Login/Login.ecced9335f76ee4f999a29d1408dba84.css"
  ...
}
```

For `2.0.0` of the plugin, running the build in production ( broken ) I see:
```
{
  "pages-Signup-Signup": "/static/pages-Signup-Signup.7656d3ca4adc6fd6127d1e9100985d9a.css",
  "pages-Login-Login": "/static/pages-Login-Login.ecced9335f76ee4f999a29d1408dba84.css",
   ...
}
```

You can repro the issue on this branch of my project by building and running in ~production~ dev or production mode: https://github.com/dtonys/universal-web-boilerplate/tree/css-broken

I'm guessing this has something to do with importCss.

**Comment by dtonys** [comment] 2018-05-20 01:59
On further inspection I reproduced the issue in dev mode, on `2.0.0` ( disabled caching ):

On loading the Home, page the css loads fine.  On navigating to the login page, I get:

![img](https://user-images.githubusercontent.com/899077/40274890-16177436-5b97-11e8-8bcc-077cd28c9df3.png)

![img2](https://user-images.githubusercontent.com/899077/40274957-fa730c7a-5b98-11e8-93fa-195c754a587a.png)

![screen shot 2018-05-19 at 7 15 55 pm](https://user-images.githubusercontent.com/899077/40274968-28d6fd2e-5b99-11e8-92b2-85f5afc1a15c.png)

I see that I am serving the asset at `/static/pages-Login-Login.css`.

@zackljackson @faceyspacey any ideas?

**Comment by ScriptedAlchemy** [comment] 2018-05-20 03:47
@dtonys ill pull down the repo and take a closer look at it shortly. 

I am considering dropping CSS chunk management from the universal family as Webpack continues to enhance the build infrastructure around it. This would mean that we rely on webpack 4 and mini-css-extract to load the css chunks while the universal family handles the hard stuff :)

Ill try to pull down your repo in a few hours. Just working on a few other things with redux-first-router right now that I want to wrap

**Comment by dtonys** [comment] 2018-05-20 04:02
Oh yea, I was impatient so I already think I found the source of the problem.

Here's my output
```
var LoginPage = (0, _reactUniversalComponent2.default)((0, _universalImport3.default)({
  id: '../../pages/Login/Login',
  file: '/Users/dtonys/webapps/universal-web-boilerplate/src/components/Page/Page.js',
  load: function load() {
    return Promise.all(
      [__webpack_require__.e/* import() */(1).then(__webpack_require__.bind(null, "./src/pages/Login/Login.js")),
      (0, _importCss3.default)('pages/Login/Login', {})]).then(function (proms) {
      return proms[0];
    });
  },
  path: function path() {
    return _path3.default.join(__dirname, '../../pages/Login/Login');
  },
  resolve: function resolve() {
    return /*require.resolve*/("./src/pages/Login/Login.js");
  },
  chunkName: function chunkName() {
    return 'pages-Login-Login';
  }
}), options);
```

Chunk name is `**pages-Login-Login**` ->
 `path.replace(/\//g, '-')` logic applied here

ImportCss function calls with `(0, _importCss3.default)('**pages/Login/Login**')` ->
 `path.replace(/\//g, '-')` logic *not* applied here

Dashed logic was applied to the chunk name, but not the importCss argument.  So these two are disconnected.  And I'm assuming that's why the client side import fails here:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/8a111321accc5280b21b5229164cb2431fd59fe9/importCss.js#L17

I wonder if there is actual value in adding the dashes?  It seems like it makes the code more complicated.  I suppose you could ensure the dash logic is added here:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/8a111321accc5280b21b5229164cb2431fd59fe9/index.js#L162

That's my best guess.

**Comment by ScriptedAlchemy** [comment] 2018-05-20 04:27
@dtonys do you mind opening a PR for this and ill review it against the other scenarios

The main reason behind the move to dashes from the usual slashes is because Webpack has updated how nested chunk and dynamic imports are resolved. Webpack appears to be moving more and more toward dashed and flattened file outputs.

**Comment by dtonys** [comment] 2018-05-20 05:03
Sure, will do.

**Comment by ScriptedAlchemy** [comment] 2018-05-20 05:25
Greatly appreciated. I should get notified but please tag me just to be sure
