### ISSUE TITLE
`import(...)` statements should allow promise chains to be attached.

### ISSUE THREAD

**Issue by benjroy** [faceyspacey/babel-plugin-universal-import#37] opened 2018-03-08 19:37 UTC
Dynamic `import()` should return a `promiseCapability`, according to the [proposal](https://tc39.github.io/proposal-dynamic-import/#sec-import-calls) and [current implementations](https://developers.google.com/web/updates/2017/11/dynamic-import)

When using this babel plugin, that capability does not work.

Here is how I believe `babel-plugin-universal-import` should work.  Consider this line:
```js
import(`./groups/core`).then(({ Paragraph }) => Paragraph);
```
currently, the plugin transpiles that to this:
```js
(0, _universalImport3.default)({
  id: './groups/core',
  file: '/path/to/source/file.js',
  load: function load() {
    return Promise.all([import( /* webpackChunkName: 'groups/core' */'./groups/core'), (0, _importCss3.default)('groups/core', {})]).then(function (proms) {
      return proms[0];
    });
  },
  path: function path() {
    return _path3.default.join(__dirname, './groups/core');
  },
  resolve: function resolve() {
    return require.resolveWeak('./groups/core');
  },
  chunkName: function chunkName() {
    return 'groups/core';
  }
}).then(function (_ref) {
  var Paragraph = _ref.Paragraph;
  return Paragraph;
});
```
What it should do is attach the `then(...)` statement to the promise returned by the `load` method, like:
```js

(0, _universalImport3.default)({
  id: './groups/core',
  file: '/path/to/source/file.js',
  load: function load() {
    return Promise.all([import( /* webpackChunkName: 'groups/core' */'./groups/core'), (0, _importCss3.default)('groups/core', {})]).then(function (proms) {
      return proms[0];
    }).then(function (_ref) {
      var Paragraph = _ref.Paragraph;
      return Paragraph;
    });
  },
  path: function path() {
    return _path3.default.join(__dirname, './groups/core');
  },
  resolve: function resolve() {
    return require.resolveWeak('./groups/core');
  },
  chunkName: function chunkName() {
    return 'groups/core';
  }
});
```

that is because `universalImport` relies on the `load()` method to work: https://github.com/faceyspacey/react-universal-component/blob/master/src/requireUniversalModule.js#L124

The `import()` spec shows that it returns a promise that resolves with the module, so writing ```import(`./groups/core`).then(({ Paragraph }) => Paragraph);``` should work without any modification when using the plugin. Basically everything attached to the right-side of `import(...)`, e.g. ```.then(...).then(...).catch(...).then(...).etc('forever and ever and on and on')```

**Comment by faceyspacey** [comment] 2018-03-09 00:44
The way things are supposed to work is that the `universalImport` function makes the return *thennable*:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/universalImport.js#L6-L11

This is the the same function in the transpiled output you pasted:

```js
(0, _universalImport3.default)
```

----

I just did a test again in the universal demo, and the following worked fine:

```js
import('../PlainImportTest').then(({ Paragraph }) => console.log('PARA', { Paragraph }))
```

I've heard others have had this issue, but I can't reproduce it. I created a fork of the `universal-demo` with it working. If you can make it ***NOT*** work there, I can help fix this. Here's the fork:

https://github.com/faceyspacey/universal-demo/tree/plain-import
```
git clone https://github.com/faceyspacey/universal-demo
cd universal-demo
git checkout plain-import
```

...go to `/src/components/App.js` to see where i added the above test thennable import.

**Comment by benjroy** [comment] 2018-03-09 01:41
gladly!  https://github.com/faceyspacey/universal-demo/pull/26

>that is because `universalImport` relies on the `load()` method to work: https://github.com/faceyspacey/react-universal-component/blob/master/src/requireUniversalModule.js#L124

The buggy behavior i am describing comes from the usage of this babel-plugin with `react-universal-component` . I kinda buried the link to the line in that repo that exposes this bug in the initial description.  Maybe this is more an issue for that repo, but it seems like these two repos are designed to be used in conjunction.

**Comment by faceyspacey** [comment] 2018-03-09 02:24
CLOSING THIS. To anyone reading this: `import().then` works outside of calls to `universal`. The issue is:

`universal(import().then)`. You can't `.then` inside that call where the argument is. Use `options.key` to destructure the resolution of `import()` instead. ..That likely won't be changing any time soon. Rather, time will be spent making a new API better suited to "Suspense" aka React Async once released. Cheers everyone!

**Closed as completed by faceyspacey** 2018-03-09 02:24 UTC
